spring:
  application:
    name: employee-service-client

server:
  port: 8666


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8181/eureka/
  instance:
    hostname: 127.0.0.1
    